name: Terraform CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

      - name: Terraform Format Check
        run: cd terraform/ && terraform fmt -check

      - name: Terraform Validate
        run: cd terraform/ && terraform validate

      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Plan
        run: cd terraform/ && terraform plan

      - name: Terraform Apply
        run: cd terraform/ && terraform apply -auto-approve
